---

- name: Configuring our file importer instance
  hosts: localhost
  connection: local
  become: true

  pre_tasks:

    - name: Update yum
      ansible.builtin.yum:
        packages: '*'
        state: latest

    - name: Install some packages
      ansible.builtin.yum:
        name:
          - https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
        state: present

    - name: Create users
      ansible.builtin.user:
        name: "{{ user }}"
        groups: "wheel, admin"
        append: true
        state: present
        password: "{{  lookup('aws_ssm', '{{ prefix }}/importer/ssh/{{ user }}/password', region='eu-west-2' ) | password_hash('sha512', '{{ password_salt }}' ) }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user

    - name: Create authorized_keys file per user
      ansible.builtin.copy:
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        content: "{{  lookup('aws_ssm', '{{ prefix }}/importer/ssh/{{ user }}/public_key', region='eu-west-2' ) }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        remote_src: true
        mode: '0400'
      loop: "{{ users }}"
      loop_control:
        loop_var: user

    - name: Update /etc/sudoers to allow wheel group to have passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^%wheel	ALL=(ALL)	ALL"
        line: "%wheel	ALL=(ALL)	NOPASSWD:ALL"

    - name: Update the /etc/sshd config file to listen on another port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Port 22$"
        line: "Port 2222"
      register: sshd_config

    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: sshd_config is changed

...
