---

users:
  - name: bjpirt
    groups:
      - admin
      - nfs_users
  - name: bminnie
    groups:
      - wheel
      - admin
      - nfs_users
  - name: randrews
    groups:
      - admin
      - nfs_users
...
